"use client";
import { analyzeWithAI, getSubscription } from "@/lib/api";
import { useAuth } from "@/provider/AuthProvider";
import toast from "react-hot-toast";
import React, { useEffect, useState } from "react";
import Link from "next/link";
import { Sparkles, Loader } from "lucide-react";
import { useParams } from "next/navigation";
import AIGenerated from "../_components/AIGenerated";

const RetailAIAnalysis = ({ analysis, spreadsheet_type }) => {
  const { fileId } = useParams();
  const { user, session, loading: authLoading } = useAuth();
  const [subscription, setSubscription] = useState(null);
  const [subscriptionError, setSubscriptionError] = useState(null);
  const [subscriptionLoading, setSubscriptionLoading] = useState(false);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const handleAnalyzeWithAI = async () => {
    if (!session?.access_token) {
      toast.error("You must be authenticated to perform this action.");
      return;
    }
    setIsAnalyzing(true);
    toast.loading("Analyzing your data...", { id: "analyzeToast" });

    try {
      await analyzeWithAI(session, fileId);
      toast.success("Analysis successful!", { id: "analyzeToast" });
    } catch (error) {
      toast.error(error.message, { id: "analyzeToast" });
      console.error("File analysis error:", error);
    } finally {
      setIsAnalyzing(false);
    }
  };

  const subscriptionStatus = async () => {
    setSubscriptionLoading(true);
    setSubscriptionError(null);

    try {
      const data = await getSubscription(session);
      setSubscription(data);
    } catch (error) {
      setSubscriptionError(error.message);
    } finally {
      setSubscriptionLoading(false);
    }
  };

  useEffect(() => {
    if (session) {
      subscriptionStatus();
    }
  }, [session]);

  const isActive =
    subscription?.status === "active" && subscription?.plan !== "free";
  const showAnalysis = analysis !== null;
  const isLocked = !isActive && showAnalysis;

  return (
    <div className="relative w-full mx-auto p-4 md:p-8 bg-gray-900 rounded-3xl shadow-xl border border-gray-700">
      <div
        className={`transition-all duration-500 ease-in-out ${
          isLocked ? "filter blur-sm pointer-events-none" : ""
        }`}
      >
        {showAnalysis ? (
          <div className="text-gray-200">
            <h2 className="text-2xl font-bold mb-4 text-blue-400">
              Your Retail AI Analysis
            </h2>
            <p className="font-light text-gray-400">
              Here is the detailed Operations insight generated by the AI model
              based on your uploaded data. .
            </p>
            <AIGenerated data={analysis} />
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center p-8 text-center text-gray-400">
            <Sparkles size={48} className="mb-4 text-blue-500" />
            <p className="text-lg">
              Ready to get insights from your Retail data?
            </p>
            <p className="text-sm mt-2">
              Click the button below to start the AI analysis.
            </p>
            <button
              onClick={handleAnalyzeWithAI}
              disabled={isAnalyzing}
              className="mt-8 inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold rounded-full shadow-lg transition-all duration-300 ease-in-out transform hover:scale-105 hover:shadow-2xl focus:outline-none focus:ring-4 focus:ring-blue-500 focus:ring-opacity-75 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isAnalyzing ? (
                <>
                  <Loader className="h-5 w-5 mr-2 animate-spin" />
                  Analyzing...
                </>
              ) : (
                <>
                  <Sparkles className="h-5 w-5 mr-2" />
                  Analyze with AI
                </>
              )}
            </button>
          </div>
        )}
      </div>

      {/* Overlay for locked content */}
      {isLocked && (
        <div className="absolute inset-0 flex flex-col items-center justify-center bg-gray-900/80 rounded-3xl backdrop-blur-sm">
          <p className="text-white text-xl font-semibold mb-4 text-center">
            Upgrade to view your detailed analysis.
          </p>
          <p className="text-gray-400 mb-6 text-center">
            Unlock powerful insights and advanced features with a premium
            subscription.
          </p>
          <Link
            href="/subscription"
            className="inline-flex items-center px-6 py-3 bg-white text-gray-900 font-bold rounded-full shadow-lg transition-transform duration-300 hover:scale-105 hover:bg-gray-200"
          >
            Upgrade Now
          </Link>
        </div>
      )}
    </div>
  );
};

export default RetailAIAnalysis;
